"""initial schema

Revision ID: 8c37345eac39
Revises: 
Create Date: 2026-07-08 09:57:34.094984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c37345eac39'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('role_title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('jd_text', sa.Text(), nullable=False),
    sa.Column('jd_source_type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('SOURCED', 'TAILORING', 'READY_FOR_REVIEW', 'APPROVED', 'APPLIED', 'EMAILED', 'INTERVIEW', 'OFFER', 'REJECTED', name='jobstatus', native_enum=False), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('gmail_draft_id', sa.String(), nullable=True),
    sa.Column('ats_source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('linkedin_url', sa.String(), nullable=False),
    sa.Column('github_url', sa.String(), nullable=False),
    sa.Column('portfolio_url', sa.String(), nullable=False),
    sa.Column('resume_original_filename', sa.String(), nullable=True),
    sa.Column('resume_raw_text', sa.Text(), nullable=True),
    sa.Column('resume_uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tailoring_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('run_type', sa.Enum('KEYWORDS', 'RESUME', 'COVER_LETTER', 'FULL', name='runtype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', name='runstatus', native_enum=False), nullable=False),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cover_letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('tailoring_run_id', sa.Integer(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tailoring_run_id'], ['tailoring_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tailored_resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('tailoring_run_id', sa.Integer(), nullable=True),
    sa.Column('resume_json', sa.Text(), nullable=False),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('warnings_json', sa.Text(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tailoring_run_id'], ['tailoring_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tailored_resumes')
    op.drop_table('cover_letters')
    op.drop_table('tailoring_runs')
    op.drop_table('profile')
    op.drop_table('jobs')
    # ### end Alembic commands ###
